// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM0msisWMzb8eCzuzmszZs13Fdi2GvZYs',
    appId: '1:574372711410:web:8c859c005a1df0f9ff796b',
    messagingSenderId: '574372711410',
    projectId: 'trackexpense-823ae',
    authDomain: 'trackexpense-823ae.firebaseapp.com',
    storageBucket: 'trackexpense-823ae.appspot.com',
    measurementId: 'G-B73ZV3ZTET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfwXeneFygiXXpxC0msxNzF2SGoHJBI_E',
    appId: '1:574372711410:android:efa00d69042162b8ff796b',
    messagingSenderId: '574372711410',
    projectId: 'trackexpense-823ae',
    storageBucket: 'trackexpense-823ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH4aIGbADBdQixrlZiZDh26vnAGDUkBAY',
    appId: '1:574372711410:ios:1904669027ef381dff796b',
    messagingSenderId: '574372711410',
    projectId: 'trackexpense-823ae',
    storageBucket: 'trackexpense-823ae.appspot.com',
    iosClientId: '574372711410-5f7lcunk5c3ngdp7g2tko3kot1akm3bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.newTrackexpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH4aIGbADBdQixrlZiZDh26vnAGDUkBAY',
    appId: '1:574372711410:ios:ce81458a906711d0ff796b',
    messagingSenderId: '574372711410',
    projectId: 'trackexpense-823ae',
    storageBucket: 'trackexpense-823ae.appspot.com',
    iosClientId: '574372711410-f9l6khumildrp67if9g4a40odfs1g5h1.apps.googleusercontent.com',
    iosBundleId: 'com.example.newTrackexpense.RunnerTests',
  );
}
